"""add incident weather fields

Revision ID: b7f31d9c4a62
Revises: 9f4c2b7a1d10
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "b7f31d9c4a62"
down_revision: str | None = "9f4c2b7a1d10"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.add_column(
        "incidents",
        sa.Column(
            "weather_status",
            sa.String(length=20),
            server_default="pending",
            nullable=False,
        ),
    )
    op.add_column(
        "incidents",
        sa.Column(
            "weather_enriched_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
    )
    op.add_column(
        "incidents",
        sa.Column(
            "weather_requested_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
    )
    op.add_column(
        "incidents",
        sa.Column(
            "weather_point_source",
            sa.String(length=20),
            nullable=True,
        ),
    )
    op.add_column(
        "incidents",
        sa.Column(
            "weather_forecast_source",
            sa.String(length=20),
            nullable=True,
        ),
    )
    op.add_column(
        "incidents",
        sa.Column(
            "nws_office",
            sa.String(length=10),
            nullable=True,
        ),
    )
    op.add_column(
        "incidents",
        sa.Column(
            "nws_grid_id",
            sa.String(length=10),
            nullable=True,
        ),
    )
    op.add_column(
        "incidents",
        sa.Column(
            "nws_grid_x",
            sa.Integer(),
            nullable=True,
        ),
    )
    op.add_column(
        "incidents",
        sa.Column(
            "nws_grid_y",
            sa.Integer(),
            nullable=True,
        ),
    )
    op.add_column(
        "incidents",
        sa.Column(
            "weather_time_zone",
            sa.String(length=100),
            nullable=True,
        ),
    )
    op.add_column(
        "incidents",
        sa.Column(
            "weather_radar_station",
            sa.String(length=20),
            nullable=True,
        ),
    )
    op.add_column(
        "incidents",
        sa.Column(
            "weather_forecast_url",
            sa.Text(),
            nullable=True,
        ),
    )
    op.add_column(
        "incidents",
        sa.Column(
            "weather_forecast_updated_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
    )
    op.add_column(
        "incidents",
        sa.Column(
            "weather_forecast_generated_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
    )
    op.add_column(
        "incidents",
        sa.Column(
            "weather_period_start",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
    )
    op.add_column(
        "incidents",
        sa.Column(
            "weather_period_end",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
    )
    op.add_column(
        "incidents",
        sa.Column(
            "weather_is_daytime",
            sa.Boolean(),
            nullable=True,
        ),
    )
    op.add_column(
        "incidents",
        sa.Column(
            "weather_temperature",
            sa.Numeric(
                precision=6,
                scale=2,
            ),
            nullable=True,
        ),
    )
    op.add_column(
        "incidents",
        sa.Column(
            "weather_temperature_unit",
            sa.String(length=10),
            nullable=True,
        ),
    )
    op.add_column(
        "incidents",
        sa.Column(
            "weather_precipitation_probability_percent",
            sa.Numeric(
                precision=5,
                scale=2,
            ),
            nullable=True,
        ),
    )
    op.add_column(
        "incidents",
        sa.Column(
            "weather_relative_humidity_percent",
            sa.Numeric(
                precision=5,
                scale=2,
            ),
            nullable=True,
        ),
    )
    op.add_column(
        "incidents",
        sa.Column(
            "weather_dewpoint_value",
            sa.Numeric(
                precision=6,
                scale=2,
            ),
            nullable=True,
        ),
    )
    op.add_column(
        "incidents",
        sa.Column(
            "weather_dewpoint_unit_code",
            sa.String(length=50),
            nullable=True,
        ),
    )
    op.add_column(
        "incidents",
        sa.Column(
            "weather_wind_speed",
            sa.String(length=50),
            nullable=True,
        ),
    )
    op.add_column(
        "incidents",
        sa.Column(
            "weather_wind_direction",
            sa.String(length=20),
            nullable=True,
        ),
    )
    op.add_column(
        "incidents",
        sa.Column(
            "weather_short_forecast",
            sa.String(length=255),
            nullable=True,
        ),
    )
    op.add_column(
        "incidents",
        sa.Column(
            "weather_detailed_forecast",
            sa.Text(),
            nullable=True,
        ),
    )
    op.add_column(
        "incidents",
        sa.Column(
            "weather_icon_url",
            sa.Text(),
            nullable=True,
        ),
    )

    op.create_index(
        "ix_incidents_weather_status",
        "incidents",
        ["weather_status"],
        unique=False,
    )
    op.create_index(
        "ix_incidents_nws_office",
        "incidents",
        ["nws_office"],
        unique=False,
    )


def downgrade() -> None:
    op.drop_index(
        "ix_incidents_nws_office",
        table_name="incidents",
    )
    op.drop_index(
        "ix_incidents_weather_status",
        table_name="incidents",
    )

    op.drop_column(
        "incidents",
        "weather_icon_url",
    )
    op.drop_column(
        "incidents",
        "weather_detailed_forecast",
    )
    op.drop_column(
        "incidents",
        "weather_short_forecast",
    )
    op.drop_column(
        "incidents",
        "weather_wind_direction",
    )
    op.drop_column(
        "incidents",
        "weather_wind_speed",
    )
    op.drop_column(
        "incidents",
        "weather_dewpoint_unit_code",
    )
    op.drop_column(
        "incidents",
        "weather_dewpoint_value",
    )
    op.drop_column(
        "incidents",
        "weather_relative_humidity_percent",
    )
    op.drop_column(
        "incidents",
        "weather_precipitation_probability_percent",
    )
    op.drop_column(
        "incidents",
        "weather_temperature_unit",
    )
    op.drop_column(
        "incidents",
        "weather_temperature",
    )
    op.drop_column(
        "incidents",
        "weather_is_daytime",
    )
    op.drop_column(
        "incidents",
        "weather_period_end",
    )
    op.drop_column(
        "incidents",
        "weather_period_start",
    )
    op.drop_column(
        "incidents",
        "weather_forecast_generated_at",
    )
    op.drop_column(
        "incidents",
        "weather_forecast_updated_at",
    )
    op.drop_column(
        "incidents",
        "weather_forecast_url",
    )
    op.drop_column(
        "incidents",
        "weather_radar_station",
    )
    op.drop_column(
        "incidents",
        "weather_time_zone",
    )
    op.drop_column(
        "incidents",
        "nws_grid_y",
    )
    op.drop_column(
        "incidents",
        "nws_grid_x",
    )
    op.drop_column(
        "incidents",
        "nws_grid_id",
    )
    op.drop_column(
        "incidents",
        "nws_office",
    )
    op.drop_column(
        "incidents",
        "weather_forecast_source",
    )
    op.drop_column(
        "incidents",
        "weather_point_source",
    )
    op.drop_column(
        "incidents",
        "weather_requested_at",
    )
    op.drop_column(
        "incidents",
        "weather_enriched_at",
    )
    op.drop_column(
        "incidents",
        "weather_status",
    )
